name: CI
on:
    pull_request:
        branches: [master]
    push:
        branches: [master]
jobs:
    Lint-Files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 12
            - run: npm ci
            - run: npm run lint
            - run: ( cd ./nest && npm ci && npm run build && npm run start:prod )
            - run: ( cd ./frontend && npm ci && npm run build )
            - run: ( cd ./discord-bot && npm ci )
