  name: CI
on:
    pull_request:
        branches: [master]
    push:
        branches: [master]
jobs:
    Lint-Files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 12
            - run: npm ci
          # - run: ( cd ./client && npm ci )
          # - run: ( cd ./server && npm ci )
            - run: ( cd ./discord-bot && npm ci )
          # - run: ( cd ./client && npm run build )
            - run: npm run lint     
