name: Heroku Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.SERVER_API_KEY}}
          heroku_app_name: "coolbotlistapi"
          heroku_email: ${{secrets.SERVER_EMAIL}} 
        
      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.BOT_API_KEY}}
          heroku_app_name: "coolbotlistbot"
          heroku_email: ${{secrets.BOT_EMAIL}}
