name: Lint Files
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
                with:
                    node-version: 12
            - name: Install modules
              run: npm ci
            - name: Run ESLint
              run: npm run lint
