name: Lint Files
on:
    pull_request:
        branches: [master]
jobs:
    Lint-Files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 12
            - name: Install Modules
              run: npm ci
            - name: Run ESLint
              run: npm run lint
